name: dhina
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: any  
  share: ^0.5.3
  webview_flutter: 0.3.14
  path_provider: any
  dio: any
  shared_preferences: any
  flare_flutter: any
  flutter_webview_plugin: any
  http: any
  device_info: 0.3.0
  package_info: ^0.4.0+3
  connectivity: ^0.4.4+1
  fluttertoast: ^3.1.3
  carousel_slider: ^0.0.3
  flutter_rating_bar: ^3.0.0
  rating_bar: ^0.2.0
  rating_dialog: ^1.0.0
  url_launcher:
  like_button: ^0.1.9
  clipboard_manager: ^0.0.1
  cupertino_icons: ^0.1.2
  rflutter_alert: ^1.0.2
  esys_flutter_share: ^1.0.2
  seekbar: ^0.0.2
  splashscreen:
  flutter_local_notifications: ^0.8.4+3
  rxdart: ^0.22.6
  dart_random_choice: ^0.0.2
  intl: ^0.16.0
  intent: ^1.1.0
  # intl: ^0.16.0

  # launch_review: ^2.0.0
  

  transformer_page_view: ^0.1.6


# flutter_seekbar:
#     path: ../
  





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  launch_review: ^2.0.0


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/thirukural_round.png"  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - PrivacyPolicy.html
    - privacy.js
    - 123.html
    - modi_kural_comp.db
    - old_modi_kural_comp.db
    - complete1.json
    - PrivacyPolicy.js
    - valluvar.png
    - valluvar.jpeg
    - play.png
    - play1.png
    - skip.png
    - category.png
    - search.png
    - gobutton.png
    - tamil_calendar.webp
    - spalsh_image.png
    - star.png
    - protection.png
    - feedback.png
    - share.png
    - rate.png
    - home.png
    - gotoSearch.png
    - thirukural_round.png
    - front.png
    - ads_icon.png
    - ads.png
    - ad.png
    - ad1.png
    - advertisement.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # module:
   
  #   androidX: true 